# Generated by Django 4.2.3 on 2023-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_author_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpromotion',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
